name: "DECP"
output_dir: "docs"
navbar:
  title: "Données essentielles de la commande publique"
  left:
  - text: "Home"
   href: index.html
  - text: "DECP"
   href: DECP.html
output:
  html_document:
 theme: cosmo
